### ISSUE TITLE
Xamarin.Android Support

### ISSUE THREAD

**Issue by PawKanarek** [aws-samples/amazon-ivs-player-android-sample#2]
Is it possible that this player will be available on Xamarin.Android? Or do you plan on adding the official Bindings for Xamarin.Android to the native com.amazonaws.ivs.player library?

**Comment by ysshin** [comment]
Hi, @PawKanarek , we don't currently provide official bindings for Xamarin, but I've shared your feedback with our internal teams. Thank you!
